param(
    [string]$ObsVersion = '32.0.4',
    [string]$ObsDirectory = 'C:\Program Files\obs-studio'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$cache = Join-Path $root ".tools\obs-sdk-$ObsVersion"
$archive = Join-Path $cache "OBS-Studio-$ObsVersion-Sources.tar.gz"
$source = Join-Path $cache "obs-studio-$ObsVersion-sources\libobs"
$artifact = Join-Path $root "obs-plugin\artifacts\obs-$ObsVersion\beatblock-together-obs.dll"
$obsDll = Join-Path $ObsDirectory 'bin\64bit\obs.dll'
$expectedHashes = @{
    '32.0.4' = 'D9E62EA24305FBFE14C69A6422DE1525FE84DA232DF2CC0D7E4601A840BDBBA8'
}

if (-not $expectedHashes.ContainsKey($ObsVersion)) {
    throw "OBS $ObsVersion is not pinned in this build script. Review it and add its official source checksum first."
}
if (-not (Test-Path $obsDll)) {
    throw "OBS runtime was not found at $obsDll"
}
New-Item -ItemType Directory -Force $cache | Out-Null
if (-not (Test-Path $archive)) {
    $url = "https://github.com/obsproject/obs-studio/releases/download/$ObsVersion/OBS-Studio-$ObsVersion-Sources.tar.gz"
    curl.exe -L --fail --output $archive $url
    if ($LASTEXITCODE -ne 0) { throw "OBS source download failed" }
}
$actualHash = (Get-FileHash $archive -Algorithm SHA256).Hash
if ($actualHash -ne $expectedHashes[$ObsVersion]) {
    throw "OBS source checksum mismatch: expected $($expectedHashes[$ObsVersion]), got $actualHash"
}
if (-not (Test-Path $source)) {
    tar -xzf $archive -C $cache
    if ($LASTEXITCODE -ne 0) { throw "OBS source extraction failed" }
}

# obsconfig.h is normally generated by OBS' full CMake build. This plugin only
# needs the release/beta constants from that generated header.
@"
#pragma once
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
"@ | Set-Content -Encoding ascii (Join-Path $source 'obsconfig.h')

$vswhere = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path $vswhere)) { throw 'Visual Studio Build Tools were not found' }
$visualStudio = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $visualStudio) { throw 'The Visual C++ x64 toolchain is not installed' }
$devCommand = Join-Path $visualStudio 'Common7\Tools\VsDevCmd.bat'

# Generate an import library from the exact installed OBS runtime so the plugin
# cannot accidentally link against a different libobs ABI.
$exports = cmd.exe /d /s /c "`"$devCommand`" -arch=x64 >nul && dumpbin /nologo /exports `"$obsDll`""
$names = $exports | ForEach-Object {
    if ($_ -match '^\s+\d+\s+[0-9A-F]+\s+[0-9A-F]+\s+(\S+)') { $Matches[1] }
}
if ($names.Count -lt 100) { throw 'Could not read the OBS export table' }
$definition = Join-Path $cache 'obs.def'
@('LIBRARY obs', 'EXPORTS') + ($names | ForEach-Object { "  $_" }) |
    Set-Content -Encoding ascii $definition
$importLibrary = Join-Path $cache 'obs.lib'
cmd.exe /d /s /c "`"$devCommand`" -arch=x64 >nul && lib /nologo /def:`"$definition`" /machine:x64 /out:`"$importLibrary`""
if ($LASTEXITCODE -ne 0) { throw 'OBS import-library generation failed' }

$build = Join-Path $cache 'build'
New-Item -ItemType Directory -Force $build | Out-Null
$pluginSource = Join-Path $root 'obs-plugin\src\plugin.c'
$batch = Join-Path $cache 'compile.cmd'
@"
@echo off
call "$devCommand" -arch=x64 >nul
if errorlevel 1 exit /b %errorlevel%
cl /nologo /LD /O2 /MD /std:c17 /DUNICODE /D_UNICODE /I"$source" /I"$(Split-Path -Parent $source)\deps\w32-pthreads" /Fo"$build\\" /Fe"$build\beatblock-together-obs.dll" "$pluginSource" "$importLibrary" /link /INCREMENTAL:NO
"@ | Set-Content -Encoding ascii $batch
cmd.exe /d /c $batch
if ($LASTEXITCODE -ne 0) { throw 'OBS plugin compilation failed' }

New-Item -ItemType Directory -Force (Split-Path -Parent $artifact) | Out-Null
Copy-Item (Join-Path $build 'beatblock-together-obs.dll') $artifact -Force
Write-Host "Built $artifact"
Write-Host "SHA-256 $((Get-FileHash $artifact -Algorithm SHA256).Hash)"
