param(
    [string]$ObsVersion = '32.0.4',
    [string]$ObsDirectory,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'release-utils.ps1')
$cache = Join-Path $root ".tools\obs-sdk-$ObsVersion"
$sourceArchive = Join-Path $cache "OBS-Studio-$ObsVersion-Sources.tar.gz"
$runtimeArchive = Join-Path $cache "OBS-Studio-$ObsVersion-Windows-x64.zip"
$source = Join-Path $cache "obs-studio-$ObsVersion-sources\libobs"
$runtimeRoot = Join-Path $cache 'obs-runtime'
if (-not $OutputPath) {
    $OutputPath = Join-Path $root 'artifacts\obs\beatblock-online-obs.dll'
}

# Both checksums are published on the corresponding official OBS release.
$versions = @{
    '32.0.4' = @{
        Source = 'D9E62EA24305FBFE14C69A6422DE1525FE84DA232DF2CC0D7E4601A840BDBBA8'
        Windows = 'FD367A7F156319426F1A600720C1288AD0011DA168DFF41E0F94DBB18CC1DC0F'
    }
}
if (-not $versions.ContainsKey($ObsVersion)) {
    throw "OBS $ObsVersion is not pinned. Review the official release and add both checksums first."
}

function Get-PinnedFile {
    param([string]$Url, [string]$Path, [string]$ExpectedHash)
    New-Item -ItemType Directory -Force (Split-Path -Parent $Path) | Out-Null
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        & curl.exe -L --fail --output $Path $Url
        if ($LASTEXITCODE -ne 0) { throw "Download failed: $Url" }
    }
    $actualHash = Get-Sha256Hex -LiteralPath $Path
    if ($actualHash -ne $ExpectedHash) {
        throw "Checksum mismatch for $Path. Expected $ExpectedHash, got $actualHash."
    }
}

$releaseBase = "https://github.com/obsproject/obs-studio/releases/download/$ObsVersion"
Get-PinnedFile `
    "$releaseBase/OBS-Studio-$ObsVersion-Sources.tar.gz" `
    $sourceArchive `
    $versions[$ObsVersion].Source

if (-not (Test-Path -LiteralPath $source -PathType Container)) {
    tar -xzf $sourceArchive -C $cache
    if ($LASTEXITCODE -ne 0) { throw 'OBS source extraction failed.' }
}

if ($ObsDirectory) {
    $obsDll = Join-Path $ObsDirectory 'bin\64bit\obs.dll'
} else {
    Get-PinnedFile `
        "$releaseBase/OBS-Studio-$ObsVersion-Windows-x64.zip" `
        $runtimeArchive `
        $versions[$ObsVersion].Windows
    if (-not (Test-Path -LiteralPath $runtimeRoot -PathType Container)) {
        Expand-Archive -LiteralPath $runtimeArchive -DestinationPath $runtimeRoot
    }
    $obsDll = Get-ChildItem -LiteralPath $runtimeRoot -Filter obs.dll -File -Recurse |
        Where-Object { $_.FullName -match '[\\/]bin[\\/]64bit[\\/]obs\.dll$' } |
        Select-Object -First 1 -ExpandProperty FullName
}
if (-not $obsDll -or -not (Test-Path -LiteralPath $obsDll -PathType Leaf)) {
    throw 'The pinned OBS x64 runtime did not contain bin\64bit\obs.dll.'
}

# obsconfig.h is normally generated by OBS' full CMake build. This plugin only
# needs the release/beta constants from that generated header.
@"
#pragma once
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
"@ | Set-Content -Encoding ascii (Join-Path $source 'obsconfig.h')

$vswhere = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path -LiteralPath $vswhere -PathType Leaf)) {
    throw 'Visual Studio Build Tools were not found.'
}
$visualStudio = & $vswhere -latest -products * `
    -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    -property installationPath
if (-not $visualStudio) { throw 'The Visual C++ x64 toolchain is not installed.' }
$devCommand = Join-Path $visualStudio 'Common7\Tools\VsDevCmd.bat'

# Generate an import library from the exact checksum-pinned OBS runtime so the
# plugin cannot accidentally link against a different libobs ABI.
$exports = cmd.exe /d /s /c "`"$devCommand`" -arch=x64 >nul && dumpbin /nologo /exports `"$obsDll`""
$names = $exports | ForEach-Object {
    if ($_ -match '^\s+\d+\s+[0-9A-F]+\s+[0-9A-F]+\s+(\S+)') { $Matches[1] }
}
if ($names.Count -lt 100) { throw 'Could not read the OBS export table.' }
$definition = Join-Path $cache 'obs.def'
@('LIBRARY obs', 'EXPORTS') + ($names | ForEach-Object { "  $_" }) |
    Set-Content -Encoding ascii $definition
$importLibrary = Join-Path $cache 'obs.lib'
cmd.exe /d /s /c "`"$devCommand`" -arch=x64 >nul && lib /nologo /def:`"$definition`" /machine:x64 /out:`"$importLibrary`""
if ($LASTEXITCODE -ne 0) { throw 'OBS import-library generation failed.' }

$build = Join-Path $cache 'build'
New-Item -ItemType Directory -Force $build | Out-Null
$pluginSource = Join-Path $root 'obs-plugin\src\plugin.c'
$batch = Join-Path $cache 'compile.cmd'
@"
@echo off
call "$devCommand" -arch=x64 >nul
if errorlevel 1 exit /b %errorlevel%
cl /nologo /LD /O2 /MD /std:c17 /DUNICODE /D_UNICODE /I"$source" /I"$(Split-Path -Parent $source)\deps\w32-pthreads" /Fo"$build\\" /Fe"$build\beatblock-online-obs.dll" "$pluginSource" "$importLibrary" /link /INCREMENTAL:NO
"@ | Set-Content -Encoding ascii $batch
cmd.exe /d /c $batch
if ($LASTEXITCODE -ne 0) { throw 'OBS plugin compilation failed.' }

$built = Join-Path $build 'beatblock-online-obs.dll'
New-Item -ItemType Directory -Force (Split-Path -Parent $OutputPath) | Out-Null
Copy-Item -LiteralPath $built -Destination $OutputPath -Force
$artifactHash = Get-Sha256Hex -LiteralPath $OutputPath
$sourceHash = Get-Sha256Hex -LiteralPath $pluginSource
$manifestPath = [System.IO.Path]::ChangeExtension($OutputPath, '.build.json')
# The installer builder consumes this manifest to prove that an ignored DLL
# was produced from the current reviewed C source, not left over from an older
# checkout. Write UTF-8 without a BOM so PowerShell 5 and Node agree on JSON.
$manifest = [ordered]@{
    schemaVersion = 1
    obsVersion = $ObsVersion
    sourcePath = 'obs-plugin/src/plugin.c'
    sourceSha256 = $sourceHash.ToLowerInvariant()
    artifactSha256 = $artifactHash.ToLowerInvariant()
} | ConvertTo-Json
[System.IO.File]::WriteAllText(
    $manifestPath,
    $manifest + [Environment]::NewLine,
    (New-Object System.Text.UTF8Encoding($false))
)
Write-Host "Built $OutputPath"
Write-Host "SHA-256 $artifactHash"
Write-Host "Recorded source provenance in $manifestPath"
